### ISSUE TITLE
[Feat] Add enabled true/false in config file

### ISSUE THREAD

**Issue by neoteknic** [marvinlabs/laravel-discord-logger#10]
Hello, awesome package ! But can you jsut add an enabled feature in config ? Thank you !

**Comment by vpratfr** [comment]
I don't understand why you would need that.

You can simply remove that logger from the configuration if not needed

>

**Comment by neoteknic** [comment]
easier to have it in a .env , for dev/prod website for example bug it's ok with empty webhook url

**Comment by neoteknic** [comment]
Can you just remove the exception when no webhook url ? Because it spam the laravel.log (emergency logger). Or add and "enabled=>true" configuration (like laravel-debugbar) ?

**Comment by vpratfr** [comment]
If you want to change that from a .env file, simply change the logger (have a stack logger in production which includes discord + a stack logger in dev which does not). You can provide multiple log channels in the logging configuration file.

I do not want to add a setting to enable the package, sorry.
