### ISSUE TITLE
Include the system's ip when logging

### ISSUE THREAD

**Issue by jhemmmm** [marvinlabs/laravel-discord-logger#14]
Hello,

I've been receiving quite a lot of problem with the logger. SInce I do have multiple running servers to run the my laravel app and it's on load balancer. I don't know which server is getting the errors.

**Comment by vpratfr** [comment]
Hi,

You can simply add a processor to Monolog. That will be used to push extra context to all your log messages (bonus: it will not only do that for Discord but for all other channels too)

See: https://seldaek.github.io/monolog/doc/01-usage.html#using-processors

**Comment by jhemmmm** [comment]
Thanks, how do I do this. laravel does not seem to have a documentation about using processors.

**Comment by vpratfr** [comment]
You can try to post your question on stackoverflow, pretty sure you'll get
some pointers there. And having a look at the laravel source code around
the log facade would also help.

>
