### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by a7md** [marvinlabs/laravel-discord-logger#21]
Hello, 

I really like this package and i use it in my applications to get the latest errors and fix them asap, but sometimes the errors spams, and i have jobs, so the discord logger gives an exception and it stops the jobs from working, because of the error exception.

so i hope there is an exception bypass to the discord rate limit, i mean by that if an error happened and discord rate limited the hook, it does not stop the app jobs from working, it pass the error.

Thank you very much again for such good & helpful package like this.

**Comment by vpratfr** [comment]
I would be open to a pull request if you could have a look. I have little time to get that implemented but I too encountered the same problem on a project of mine.

**Comment by CaptainCannabis** [comment]
Same here, loggin in jobs and stuff like that to a devlog discord channel for delightful (yeah i know about sentry and tools like that) exception fixing. But sometimes rate limit kicks in. Would it be possible to avoid that by letting the discord-logger count the send messages and than, if rate limit would be reached log to file instead?

**Comment by vpratfr** [comment]
Hi,

As I said, I would happily welcome a (well tested) PR.

We could indeed for example keep a hash of the last 10 messages sent, along with the timestamp. 

Then, before sending a message, check if the hash is already in our history and if the timestamp is older than 1 minutes for instance.

That way we would avoid sending the same messages too often.

**Comment by hsmfawaz** [comment]
the simplest way to solve this problem by adding 
MessageCouldNotBeSent Exception to $dontReport Method in the handler.php
like this
```PHP
class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        MessageCouldNotBeSent::class,
    ];
....
}
```

**Comment by sammyaxe** [comment]
Yeah, this is a pretty big problem, especially in prod, because it causes the application to crash. Maybe it would make sense to simply add try catch if application is in prod mode, to avoid crashing it?

**Comment by Xinecraft** [comment]
crashing a job just coz logger fail to communicate with discord seems to be a problem. Apart from 429 there might be other discord sided issue too.
Just ignoring feels better.

_Lemme know if u open for a PR to just ignore error instead of throwing Exception._

**Comment by vpratfr** [comment]
Hi

Yes, a PR would be welcome if we'll tested.

Would be good to be able to turn on/off ignoring those discord exceptions
with an env variable or config value.

That way we can ignore in prod, while still getting them in dev or staging
app.

**Comment by Xinecraft** [comment]
Just noticed there is an option in the `stack` driver in Laravel already to ignore exceptions. 😅
![image](https://user-images.githubusercontent.com/3089863/221089071-5a83f600-c53d-4fe2-b61d-94d2342be19b.png)



But still, if someone needs to disable discord specifically or doesn't use stack driver then here is PR for it. #35
