### ISSUE TITLE
Support Laravel 6.x and php 8

### ISSUE THREAD

**Issue by tomaszKit** [marvinlabs/laravel-discord-logger#26]
Hello guys.

Is any chance for add new version of required packages ? 

```
"require": {
    "php": ">=7.3 | ^8.0",
    "ext-json": "*",
    "guzzlehttp/guzzle": "^6.3|^7.0|^7.5",
    "illuminate/support": "^6.0|^7.0|^8.0|^9.0"
  },
```
`  "illuminate/support": "^6.0` and `"guzzlehttp/guzzle": "^7.5",`

**Comment by AndreasSchantl** [comment]
I would recommend upgrading Laravel to a version that officially supports PHP 8. L6 doesn't.

**Comment by vpratfr** [comment]
Same recommendation here + PHP 8 is already supported by the package.
