### ISSUE TITLE
Erorr on Payload > Embeds > url on GuzzleWebHook.php on send function

### ISSUE THREAD

**Issue by indimasia** [marvinlabs/laravel-discord-logger#29]
when i try logging with discord i got error with this message
Discord web hook responded with an error (400): {\"embeds\": [\"0\"]}
when i the code on GuzzleWebHook.php on send function, its send url on payload with key embeds,
when I try post to discord without embeds url, it goes success.
Can you remove the url key on payload?

**Comment by jairdeon** [comment]
Hi, I am also having this same problem. For now, I immediately made the following apparently unlikely change:

In the file:
- `vendor/marvinlabs/laravel-discord-logger/src/DiscordLogger/Discord/Embed.php`
I commented the line 122 `// 'url' => $this->url`

With that I got the updates from Discord again.
