### ISSUE TITLE
Is it possible to change the message icon?

### ISSUE THREAD

**Issue by ameryu716** [marvinlabs/laravel-discord-logger#30]
First of all, thank you.
Thanks to this plugin, debugging in the production environment has become considerably easier.

# problem
The icon changes according to the log type, this is good.
However, every time I send an error log, I'm forced to see poop, this is terrible.

For me, poop is something I only want to see in the bathroom.
Therefore, I can only use the `debug()` type for logs sent by this plugin.
Bugs are fine for me.

# Question

Program errors are certainly poop, but I think it's fine just in your head.
I would appreciate it if you could tell me how to change it.
I'm not familiar with PHP or Laravel, is it difficult if the plugin itself needs to be changed?

Sorry for the long sentence. I am always grateful for your help.

※ Sorry, This sentence was generated by Google Translate.

**Comment by sibkod** [comment]
> 

Hi. See discord-logger config file, all icons are there
`/*
     * A set of emojis to associate to the different log levels. Set to null to disable an emoji for a given level
     */
    'emojis'     => [
        'DEBUG'     => ':beetle:',
        'INFO'      => ':bulb:',
        'NOTICE'    => ':wink:',
        'WARNING'   => ':flushed:',
        'ERROR'     => ':poop:',
        'CRITICAL'  => ':imp:',
        'ALERT'     => ':japanese_ogre:',
        'EMERGENCY' => ':skull:',
    ],`

**Comment by ameryu716** [comment]
thanks, yes i know.
Does it mean that I should edit the config file directly by myself?
Is it common sense in general (around the laravel library)?

**Comment by vpratfr** [comment]
You can publish the config file (as said in the readme) and then edit it.
Yes this is the standard way to do it on Laravel.

**Comment by ameryu716** [comment]
@vpratfr 
Thank you!
>publish the config file (as said in the readme)

it is amazing! I finally understood.
Sorry, Thank you and everyone else, for answering my low level question.
I would like to close this.
