### ISSUE TITLE
Log [discord] is not defined.

### ISSUE THREAD

**Issue by elizandropacheco** [marvinlabs/laravel-discord-logger#37]
even following all the steps in the README, the application displays the error:

Log [discord] is not defined.

Any idea?

**Comment by Chrisx84** [comment]
`// config/logging.php
'channels' => [
    //...
    'discord' => [
        'driver' => 'custom',
        'via'    => MarvinLabs\DiscordLogger\Logger::class,
        'level'  => 'debug',
        'url'    => env('LOG_DISCORD_WEBHOOK_URL'),
    ],
];`

**Comment by elizandropacheco** [comment]
Tkz.
