### ISSUE TITLE
All logs as file after a certain character length

### ISSUE THREAD

**Issue by kiritokatklian** [marvinlabs/laravel-discord-logger#40]
Currently stacktraces are logged as files if enabled in the config file. However, other logs longer than 2000 characters are sent as an embed which gets truncated. It'd be great if all logs longer than 2000 are also sent as a file just like with stacktraces.

**Comment by vpratfr** [comment]
related to #20

**Comment by kiritokatklian** [comment]
@vpratfr Sorry about that! I completely forgot about the other opened issue.
I created #41 and added two tests. Let me know if it needs anything else 👍
