### ISSUE TITLE
PHP Version requirement error

### ISSUE THREAD

**Issue by oparreche** [marvinlabs/laravel-discord-logger#48]
`public function write(array|LogRecord $record): void
    {
        if ($record instanceof LogRecord) {
            $record =  $record->toArray();
        }
        foreach($this->recordToMessage->buildMessages($record) as $message) {
            try {
                $this->discord->send($message);
            } catch (\Exception $e) {
                if (!$this->ignoreExceptions) {
                    throw $e;
                }
            }
        }
    }`
    
    This function doesn't works on PHP versions < 8.0

**Comment by vpratfr** [comment]
We will not support PHP 7.x

Sorry.
