### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by tekord** [marvinlabs/laravel-discord-logger#51]
Laravel 11 is coming. Can't install laravel-discord-logger on current master branch of the framework. I believe changing illuminate/support package version constraint will fix this.

**Comment by vpratfr** [comment]
Hi,

Feel free to submit a well tested PR. Otherwise I will do that when we
migrate our own project to L11.

Regards,

**Comment by it-saeed** [comment]
+1

**Comment by Chrisx84** [comment]
+2

**Comment by 8ctopus** [comment]
Thank you for a great package, can't wait for the update for laravel 11.x

**Comment by 8ctopus** [comment]
Thank you for taking the time to update it!
