### ISSUE TITLE
MarvinLabs\DiscordLogger\str_contains()

### ISSUE THREAD

**Issue by Jespertastesen** [marvinlabs/laravel-discord-logger#6]
![Annotation 2019-12-10 124417](https://user-images.githubusercontent.com/7554271/70526860-d008f800-1b4a-11ea-8d77-aa1991220397.png)

**Comment by vpratfr** [comment]
Would you be able to submit a PR to fix that? Needs to use Str::contains instead

**Comment by Jespertastesen** [comment]
have made a PR #7
